---
- hosts: all
  gather_facts: no
  tasks:
    - name: apt-get update
      raw: apt-get update -qq
    - name: Install python 2.7
      raw: apt-get install -qq python-minimal

- hosts: all
  gather_facts: yes
  become: yes
  roles: [ yas ]
